version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - web

  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: user
    #   MONGO_INITDB_ROOT_PASSWORD: passwd
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      # - C:\Certbot\live\emotionalstory.ddns.net:/etc/nginx/certs
      - ./emotionalstory.ddns.net:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - web

volumes:
  mongo_data:
networks:
  web:
